---
- name: Install Grafana
  hosts: hosts
  become: yes
  
  tasks:
  - name: remove apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      id: some-id-of-the-key
      state: absent

  - name: remove Grafana repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: absent

  - name: Make sure grafana is stopped
    ansible.builtin.systemd_service:
      name: grafana-server
      enabled: false
      state: stopped

  - name: Update apt cache and install grafana
    ansible.builtin.apt:
      name: grafana
      state: absent

