---
- name: Install Jenkins
  hosts: main
  become: yes
  vars:
    listen_address: 0.0.0.0
    listen_port: 9090


  tasks:
    - name: download Jenkins apt key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repo to sources.list
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian binary/
        filename: jenkins
        state: present

    - name: Update apt cache and install fontconfig
      ansible.builtin.apt:
        name: fontconfig
        update_cache: true

    - name: Update apt cache and install Java
      ansible.builtin.apt:
        name: openjdk-17-jre
        update_cache: true

    - name: Update apt cache and install Jenkins
      ansible.builtin.apt:
        name: jenkins
        update_cache: true

    - name: Make sure jenkins is started
      ansible.builtin.systemd_service:
        name: jenkins
        enabled: true
        state: started
